name: Terraform Validate

on:
  push:
    branches: [main]
    paths: ["projects/serverless-data-api/infra/**"]
  pull_request:
    branches: [main]
    paths: ["projects/serverless-data-api/infra/**"]

defaults:
  run:
    working-directory: projects/serverless-data-api/infra

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: "1.7.5"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
